// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ThingsBoardEntityGroupControllerMock is an autogenerated mock type for the ThingsBoardEntityGroupController type
type ThingsBoardEntityGroupControllerMock struct {
	mock.Mock
}

// GetEntityGroupsByType provides a mock function with given fields: groupType, token
func (_m *ThingsBoardEntityGroupControllerMock) GetEntityGroupsByType(groupType string, token string) (int, []interface{}, error) {
	ret := _m.Called(groupType, token)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(groupType, token)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 []interface{}
	if rf, ok := ret.Get(1).(func(string, string) []interface{}); ok {
		r1 = rf(groupType, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]interface{})
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(groupType, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
